version: "3.5"

services:
  putio-downloader:
    build: .
    container_name: putio-downloader
    volumes:
      - ${DOWNLOAD_DIR:-./volumes/download}:/download
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - net
    depends_on:
      - filebot-node

  filebot-node:
    image: rednoah/filebot:node
    container_name: filebot-node
    volumes:
      - type: bind
        source: ${OUTPUT_DIR:-./volumes/output}
        target: /output/
      - ${FILEBOT_VOLUME:-./volumes/filebot}:/data
      - ${DOWNLOAD_DIR:-./volumes/download}:/download
    ports:
      - 127.0.0.1:5452:5452
    networks:
      - net

networks:
  net:
    driver: bridge
